// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: helloworld/v1/greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGreeterAirdropTrade = "/helloworld.v1.Greeter/AirdropTrade"
const OperationGreeterBindWallet = "/helloworld.v1.Greeter/BindWallet"
const OperationGreeterBztDapp = "/helloworld.v1.Greeter/BztDapp"
const OperationGreeterCloseOrder = "/helloworld.v1.Greeter/CloseOrder"
const OperationGreeterDeployContract = "/helloworld.v1.Greeter/DeployContract"
const OperationGreeterGetAirdrop = "/helloworld.v1.Greeter/GetAirdrop"
const OperationGreeterGetBztOwnerAddress = "/helloworld.v1.Greeter/GetBztOwnerAddress"
const OperationGreeterGetBztVersion = "/helloworld.v1.Greeter/GetBztVersion"
const OperationGreeterGetLoginMessage = "/helloworld.v1.Greeter/GetLoginMessage"
const OperationGreeterHealth = "/helloworld.v1.Greeter/Health"
const OperationGreeterLoginWithWallet = "/helloworld.v1.Greeter/LoginWithWallet"
const OperationGreeterMarketCondition = "/helloworld.v1.Greeter/MarketCondition"
const OperationGreeterOpenOrder = "/helloworld.v1.Greeter/OpenOrder"
const OperationGreeterOrderTrade = "/helloworld.v1.Greeter/OrderTrade"
const OperationGreeterSayHello = "/helloworld.v1.Greeter/SayHello"
const OperationGreeterWalletBalance = "/helloworld.v1.Greeter/WalletBalance"

type GreeterHTTPServer interface {
	AirdropTrade(context.Context, *AirdropTradeRequest) (*AirdropTradeReply, error)
	BindWallet(context.Context, *BindWalletRequest) (*BindWalletReply, error)
	BztDapp(context.Context, *BztDappRequest) (*BztDappReply, error)
	CloseOrder(context.Context, *CloseOrderRequest) (*CloseOrderReply, error)
	DeployContract(context.Context, *DeployContractRequest) (*DeployContractReply, error)
	GetAirdrop(context.Context, *GetAirdropRequest) (*GetAirdropReply, error)
	GetBztOwnerAddress(context.Context, *GetBztOwnerAddressRequest) (*GetBztOwnerAddressReply, error)
	GetBztVersion(context.Context, *GetBztVersionRequest) (*GetBztVersionReply, error)
	GetLoginMessage(context.Context, *GetLoginMessageRequest) (*GetLoginMessageReply, error)
	Health(context.Context, *HealthCheckRequest) (*HealthCheckReply, error)
	LoginWithWallet(context.Context, *LoginRequest) (*LoginReply, error)
	MarketCondition(context.Context, *MarketConditionRequest) (*MarketConditionReply, error)
	OpenOrder(context.Context, *OpenOrderRequest) (*OpenOrderReply, error)
	OrderTrade(context.Context, *OrderTradeRequest) (*OrderTradeReply, error)
	// SayHello Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	WalletBalance(context.Context, *WalletBalanceRequest) (*WalletBalanceReply, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.GET("/helloworld/{name}/{value}", _Greeter_SayHello0_HTTP_Handler(srv))
	r.POST("/v1/bindWallet", _Greeter_BindWallet0_HTTP_Handler(srv))
	r.POST("/v1/getLoginMessage", _Greeter_GetLoginMessage0_HTTP_Handler(srv))
	r.POST("/v1/loginWithWallet", _Greeter_LoginWithWallet0_HTTP_Handler(srv))
	r.POST("/v1/walletBalance", _Greeter_WalletBalance0_HTTP_Handler(srv))
	r.POST("/v1/marketCondition", _Greeter_MarketCondition0_HTTP_Handler(srv))
	r.POST("/v1/openOrder", _Greeter_OpenOrder0_HTTP_Handler(srv))
	r.POST("/v1/closeOrder", _Greeter_CloseOrder0_HTTP_Handler(srv))
	r.POST("/v1/getAirdrop", _Greeter_GetAirdrop0_HTTP_Handler(srv))
	r.GET("/health", _Greeter_Health0_HTTP_Handler(srv))
	r.POST("/v1/orderTrade", _Greeter_OrderTrade0_HTTP_Handler(srv))
	r.POST("/v1/airdropTrade", _Greeter_AirdropTrade0_HTTP_Handler(srv))
	r.GET("/bzt/dapp", _Greeter_BztDapp0_HTTP_Handler(srv))
	r.POST("/v1/deployContract", _Greeter_DeployContract0_HTTP_Handler(srv))
	r.POST("/v1/getBztOwnerAddress", _Greeter_GetBztOwnerAddress0_HTTP_Handler(srv))
	r.GET("/bzt/version", _Greeter_GetBztVersion0_HTTP_Handler(srv))
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterSayHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_BindWallet0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindWalletRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterBindWallet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindWallet(ctx, req.(*BindWalletRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BindWalletReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_GetLoginMessage0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLoginMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterGetLoginMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLoginMessage(ctx, req.(*GetLoginMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLoginMessageReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_LoginWithWallet0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterLoginWithWallet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginWithWallet(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_WalletBalance0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WalletBalanceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterWalletBalance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WalletBalance(ctx, req.(*WalletBalanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WalletBalanceReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_MarketCondition0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarketConditionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterMarketCondition)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarketCondition(ctx, req.(*MarketConditionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MarketConditionReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_OpenOrder0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OpenOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterOpenOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OpenOrder(ctx, req.(*OpenOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OpenOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_CloseOrder0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CloseOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterCloseOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CloseOrder(ctx, req.(*CloseOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CloseOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_GetAirdrop0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAirdropRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterGetAirdrop)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAirdrop(ctx, req.(*GetAirdropRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAirdropReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_Health0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthCheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Health(ctx, req.(*HealthCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthCheckReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_OrderTrade0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OrderTradeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterOrderTrade)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OrderTrade(ctx, req.(*OrderTradeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderTradeReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_AirdropTrade0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AirdropTradeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterAirdropTrade)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AirdropTrade(ctx, req.(*AirdropTradeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AirdropTradeReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_BztDapp0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BztDappRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterBztDapp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BztDapp(ctx, req.(*BztDappRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BztDappReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_DeployContract0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeployContractRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterDeployContract)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeployContract(ctx, req.(*DeployContractRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeployContractReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_GetBztOwnerAddress0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBztOwnerAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterGetBztOwnerAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBztOwnerAddress(ctx, req.(*GetBztOwnerAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBztOwnerAddressReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_GetBztVersion0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBztVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterGetBztVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBztVersion(ctx, req.(*GetBztVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBztVersionReply)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	AirdropTrade(ctx context.Context, req *AirdropTradeRequest, opts ...http.CallOption) (rsp *AirdropTradeReply, err error)
	BindWallet(ctx context.Context, req *BindWalletRequest, opts ...http.CallOption) (rsp *BindWalletReply, err error)
	BztDapp(ctx context.Context, req *BztDappRequest, opts ...http.CallOption) (rsp *BztDappReply, err error)
	CloseOrder(ctx context.Context, req *CloseOrderRequest, opts ...http.CallOption) (rsp *CloseOrderReply, err error)
	DeployContract(ctx context.Context, req *DeployContractRequest, opts ...http.CallOption) (rsp *DeployContractReply, err error)
	GetAirdrop(ctx context.Context, req *GetAirdropRequest, opts ...http.CallOption) (rsp *GetAirdropReply, err error)
	GetBztOwnerAddress(ctx context.Context, req *GetBztOwnerAddressRequest, opts ...http.CallOption) (rsp *GetBztOwnerAddressReply, err error)
	GetBztVersion(ctx context.Context, req *GetBztVersionRequest, opts ...http.CallOption) (rsp *GetBztVersionReply, err error)
	GetLoginMessage(ctx context.Context, req *GetLoginMessageRequest, opts ...http.CallOption) (rsp *GetLoginMessageReply, err error)
	Health(ctx context.Context, req *HealthCheckRequest, opts ...http.CallOption) (rsp *HealthCheckReply, err error)
	LoginWithWallet(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	MarketCondition(ctx context.Context, req *MarketConditionRequest, opts ...http.CallOption) (rsp *MarketConditionReply, err error)
	OpenOrder(ctx context.Context, req *OpenOrderRequest, opts ...http.CallOption) (rsp *OpenOrderReply, err error)
	OrderTrade(ctx context.Context, req *OrderTradeRequest, opts ...http.CallOption) (rsp *OrderTradeReply, err error)
	SayHello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
	WalletBalance(ctx context.Context, req *WalletBalanceRequest, opts ...http.CallOption) (rsp *WalletBalanceReply, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

func (c *GreeterHTTPClientImpl) AirdropTrade(ctx context.Context, in *AirdropTradeRequest, opts ...http.CallOption) (*AirdropTradeReply, error) {
	var out AirdropTradeReply
	pattern := "/v1/airdropTrade"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterAirdropTrade))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) BindWallet(ctx context.Context, in *BindWalletRequest, opts ...http.CallOption) (*BindWalletReply, error) {
	var out BindWalletReply
	pattern := "/v1/bindWallet"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterBindWallet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) BztDapp(ctx context.Context, in *BztDappRequest, opts ...http.CallOption) (*BztDappReply, error) {
	var out BztDappReply
	pattern := "/bzt/dapp"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterBztDapp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) CloseOrder(ctx context.Context, in *CloseOrderRequest, opts ...http.CallOption) (*CloseOrderReply, error) {
	var out CloseOrderReply
	pattern := "/v1/closeOrder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterCloseOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) DeployContract(ctx context.Context, in *DeployContractRequest, opts ...http.CallOption) (*DeployContractReply, error) {
	var out DeployContractReply
	pattern := "/v1/deployContract"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterDeployContract))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) GetAirdrop(ctx context.Context, in *GetAirdropRequest, opts ...http.CallOption) (*GetAirdropReply, error) {
	var out GetAirdropReply
	pattern := "/v1/getAirdrop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterGetAirdrop))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) GetBztOwnerAddress(ctx context.Context, in *GetBztOwnerAddressRequest, opts ...http.CallOption) (*GetBztOwnerAddressReply, error) {
	var out GetBztOwnerAddressReply
	pattern := "/v1/getBztOwnerAddress"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterGetBztOwnerAddress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) GetBztVersion(ctx context.Context, in *GetBztVersionRequest, opts ...http.CallOption) (*GetBztVersionReply, error) {
	var out GetBztVersionReply
	pattern := "/bzt/version"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterGetBztVersion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) GetLoginMessage(ctx context.Context, in *GetLoginMessageRequest, opts ...http.CallOption) (*GetLoginMessageReply, error) {
	var out GetLoginMessageReply
	pattern := "/v1/getLoginMessage"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterGetLoginMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) Health(ctx context.Context, in *HealthCheckRequest, opts ...http.CallOption) (*HealthCheckReply, error) {
	var out HealthCheckReply
	pattern := "/health"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterHealth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) LoginWithWallet(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/loginWithWallet"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterLoginWithWallet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) MarketCondition(ctx context.Context, in *MarketConditionRequest, opts ...http.CallOption) (*MarketConditionReply, error) {
	var out MarketConditionReply
	pattern := "/v1/marketCondition"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterMarketCondition))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) OpenOrder(ctx context.Context, in *OpenOrderRequest, opts ...http.CallOption) (*OpenOrderReply, error) {
	var out OpenOrderReply
	pattern := "/v1/openOrder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterOpenOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) OrderTrade(ctx context.Context, in *OrderTradeRequest, opts ...http.CallOption) (*OrderTradeReply, error) {
	var out OrderTradeReply
	pattern := "/v1/orderTrade"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterOrderTrade))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) SayHello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/helloworld/{name}/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterSayHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GreeterHTTPClientImpl) WalletBalance(ctx context.Context, in *WalletBalanceRequest, opts ...http.CallOption) (*WalletBalanceReply, error) {
	var out WalletBalanceReply
	pattern := "/v1/walletBalance"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterWalletBalance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
