// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: helloworld/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         uint64                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLoginMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginMessageRequest) Reset() {
	*x = GetLoginMessageRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginMessageRequest) ProtoMessage() {}

func (x *GetLoginMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginMessageRequest.ProtoReflect.Descriptor instead.
func (*GetLoginMessageRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *GetLoginMessageRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The response message containing the greetings
type GetLoginMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      string                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginMessageReply) Reset() {
	*x = GetLoginMessageReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginMessageReply) ProtoMessage() {}

func (x *GetLoginMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginMessageReply.ProtoReflect.Descriptor instead.
func (*GetLoginMessageReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoginMessageReply) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *GetLoginMessageReply) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type BindWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindWalletRequest) Reset() {
	*x = BindWalletRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindWalletRequest) ProtoMessage() {}

func (x *BindWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindWalletRequest.ProtoReflect.Descriptor instead.
func (*BindWalletRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *BindWalletRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The response message containing the greetings
type BindWalletReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindWalletReply) Reset() {
	*x = BindWalletReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindWalletReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindWalletReply) ProtoMessage() {}

func (x *BindWalletReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindWalletReply.ProtoReflect.Descriptor instead.
func (*BindWalletReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *BindWalletReply) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BindWalletReply) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *BindWalletReply) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *LoginRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The response message containing the greetings
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{7}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type WalletBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletBalanceRequest) Reset() {
	*x = WalletBalanceRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletBalanceRequest) ProtoMessage() {}

func (x *WalletBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletBalanceRequest.ProtoReflect.Descriptor instead.
func (*WalletBalanceRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{8}
}

func (x *WalletBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TokenBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBalance) Reset() {
	*x = TokenBalance{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBalance) ProtoMessage() {}

func (x *TokenBalance) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBalance.ProtoReflect.Descriptor instead.
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{9}
}

func (x *TokenBalance) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenBalance) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type WalletBalanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenBalance        `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletBalanceReply) Reset() {
	*x = WalletBalanceReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletBalanceReply) ProtoMessage() {}

func (x *WalletBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletBalanceReply.ProtoReflect.Descriptor instead.
func (*WalletBalanceReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{10}
}

func (x *WalletBalanceReply) GetTokens() []*TokenBalance {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type MarketConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketConditionRequest) Reset() {
	*x = MarketConditionRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketConditionRequest) ProtoMessage() {}

func (x *MarketConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketConditionRequest.ProtoReflect.Descriptor instead.
func (*MarketConditionRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{11}
}

func (x *MarketConditionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketConditionRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MarketConditionRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type MarketPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Time          uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketPrice) Reset() {
	*x = MarketPrice{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPrice) ProtoMessage() {}

func (x *MarketPrice) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPrice.ProtoReflect.Descriptor instead.
func (*MarketPrice) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{12}
}

func (x *MarketPrice) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *MarketPrice) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type MarketConditionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*MarketPrice         `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketConditionReply) Reset() {
	*x = MarketConditionReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketConditionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketConditionReply) ProtoMessage() {}

func (x *MarketConditionReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketConditionReply.ProtoReflect.Descriptor instead.
func (*MarketConditionReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{13}
}

func (x *MarketConditionReply) GetPrices() []*MarketPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

type OpenOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenOrderRequest) Reset() {
	*x = OpenOrderRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrderRequest) ProtoMessage() {}

func (x *OpenOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrderRequest.ProtoReflect.Descriptor instead.
func (*OpenOrderRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{14}
}

func (x *OpenOrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OpenOrderRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OpenOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// The response message containing the greetings
type OpenOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenOrderReply) Reset() {
	*x = OpenOrderReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrderReply) ProtoMessage() {}

func (x *OpenOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrderReply.ProtoReflect.Descriptor instead.
func (*OpenOrderReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{15}
}

func (x *OpenOrderReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CloseOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       string                 `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrderRequest) Reset() {
	*x = CloseOrderRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderRequest) ProtoMessage() {}

func (x *CloseOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderRequest.ProtoReflect.Descriptor instead.
func (*CloseOrderRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{16}
}

func (x *CloseOrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CloseOrderRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CloseOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CloseOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// The response message containing the greetings
type CloseOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            string                 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrderReply) Reset() {
	*x = CloseOrderReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderReply) ProtoMessage() {}

func (x *CloseOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderReply.ProtoReflect.Descriptor instead.
func (*CloseOrderReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{17}
}

func (x *CloseOrderReply) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

type GetAirdropRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	IsClaims      uint64                 `protobuf:"varint,2,opt,name=isClaims,proto3" json:"isClaims,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAirdropRequest) Reset() {
	*x = GetAirdropRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAirdropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAirdropRequest) ProtoMessage() {}

func (x *GetAirdropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAirdropRequest.ProtoReflect.Descriptor instead.
func (*GetAirdropRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{18}
}

func (x *GetAirdropRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAirdropRequest) GetIsClaims() uint64 {
	if x != nil {
		return x.IsClaims
	}
	return 0
}

func (x *GetAirdropRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// The response message containing the greetings
type GetAirdropReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAirdropReply) Reset() {
	*x = GetAirdropReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAirdropReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAirdropReply) ProtoMessage() {}

func (x *GetAirdropReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAirdropReply.ProtoReflect.Descriptor instead.
func (*GetAirdropReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{19}
}

func (x *GetAirdropReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAirdropReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetAirdropReply) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{20}
}

type HealthCheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok" 或 "not ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReply) Reset() {
	*x = HealthCheckReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReply) ProtoMessage() {}

func (x *HealthCheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReply.ProtoReflect.Descriptor instead.
func (*HealthCheckReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTradeRequest) Reset() {
	*x = OrderTradeRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTradeRequest) ProtoMessage() {}

func (x *OrderTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTradeRequest.ProtoReflect.Descriptor instead.
func (*OrderTradeRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{22}
}

func (x *OrderTradeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderTradeRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderTradeRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// The response message containing the greetings
type OrderTradeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*OrderDetails        `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTradeReply) Reset() {
	*x = OrderTradeReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTradeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTradeReply) ProtoMessage() {}

func (x *OrderTradeReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTradeReply.ProtoReflect.Descriptor instead.
func (*OrderTradeReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{23}
}

func (x *OrderTradeReply) GetResult() []*OrderDetails {
	if x != nil {
		return x.Result
	}
	return nil
}

type OrderDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Symbol         string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OpenedPrice    string                 `protobuf:"bytes,3,opt,name=openedPrice,proto3" json:"openedPrice,omitempty"`
	ClosePrice     string                 `protobuf:"bytes,4,opt,name=closePrice,proto3" json:"closePrice,omitempty"`
	ProfitLoss     string                 `protobuf:"bytes,5,opt,name=profitLoss,proto3" json:"profitLoss,omitempty"`
	Amount         string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	UsersAddr      string                 `protobuf:"bytes,7,opt,name=usersAddr,proto3" json:"usersAddr,omitempty"`
	IsClosed       uint64                 `protobuf:"varint,8,opt,name=isClosed,proto3" json:"isClosed,omitempty"`
	OrderStartTime uint64                 `protobuf:"varint,9,opt,name=orderStartTime,proto3" json:"orderStartTime,omitempty"`
	OrderEndTime   uint64                 `protobuf:"varint,10,opt,name=orderEndTime,proto3" json:"orderEndTime,omitempty"`
	OpenTxHash     string                 `protobuf:"bytes,11,opt,name=openTxHash,proto3" json:"openTxHash,omitempty"`
	CloseTxHash    string                 `protobuf:"bytes,12,opt,name=closeTxHash,proto3" json:"closeTxHash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderDetails) Reset() {
	*x = OrderDetails{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetails) ProtoMessage() {}

func (x *OrderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetails.ProtoReflect.Descriptor instead.
func (*OrderDetails) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{24}
}

func (x *OrderDetails) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderDetails) GetOpenedPrice() string {
	if x != nil {
		return x.OpenedPrice
	}
	return ""
}

func (x *OrderDetails) GetClosePrice() string {
	if x != nil {
		return x.ClosePrice
	}
	return ""
}

func (x *OrderDetails) GetProfitLoss() string {
	if x != nil {
		return x.ProfitLoss
	}
	return ""
}

func (x *OrderDetails) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *OrderDetails) GetUsersAddr() string {
	if x != nil {
		return x.UsersAddr
	}
	return ""
}

func (x *OrderDetails) GetIsClosed() uint64 {
	if x != nil {
		return x.IsClosed
	}
	return 0
}

func (x *OrderDetails) GetOrderStartTime() uint64 {
	if x != nil {
		return x.OrderStartTime
	}
	return 0
}

func (x *OrderDetails) GetOrderEndTime() uint64 {
	if x != nil {
		return x.OrderEndTime
	}
	return 0
}

func (x *OrderDetails) GetOpenTxHash() string {
	if x != nil {
		return x.OpenTxHash
	}
	return ""
}

func (x *OrderDetails) GetCloseTxHash() string {
	if x != nil {
		return x.CloseTxHash
	}
	return ""
}

type AirdropTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirdropTradeRequest) Reset() {
	*x = AirdropTradeRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirdropTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirdropTradeRequest) ProtoMessage() {}

func (x *AirdropTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirdropTradeRequest.ProtoReflect.Descriptor instead.
func (*AirdropTradeRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{25}
}

func (x *AirdropTradeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// The response message containing the greetings
type AirdropTradeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*AirdropDetails      `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirdropTradeReply) Reset() {
	*x = AirdropTradeReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirdropTradeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirdropTradeReply) ProtoMessage() {}

func (x *AirdropTradeReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirdropTradeReply.ProtoReflect.Descriptor instead.
func (*AirdropTradeReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{26}
}

func (x *AirdropTradeReply) GetResult() []*AirdropDetails {
	if x != nil {
		return x.Result
	}
	return nil
}

type AirdropDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersAddr     string                 `protobuf:"bytes,1,opt,name=usersAddr,proto3" json:"usersAddr,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Times         string                 `protobuf:"bytes,4,opt,name=times,proto3" json:"times,omitempty"`
	TxHash        string                 `protobuf:"bytes,5,opt,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirdropDetails) Reset() {
	*x = AirdropDetails{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirdropDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirdropDetails) ProtoMessage() {}

func (x *AirdropDetails) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirdropDetails.ProtoReflect.Descriptor instead.
func (*AirdropDetails) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{27}
}

func (x *AirdropDetails) GetUsersAddr() string {
	if x != nil {
		return x.UsersAddr
	}
	return ""
}

func (x *AirdropDetails) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *AirdropDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AirdropDetails) GetTimes() string {
	if x != nil {
		return x.Times
	}
	return ""
}

func (x *AirdropDetails) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type BztDappRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BztDappRequest) Reset() {
	*x = BztDappRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BztDappRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BztDappRequest) ProtoMessage() {}

func (x *BztDappRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BztDappRequest.ProtoReflect.Descriptor instead.
func (*BztDappRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{28}
}

type BztDappReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*DataDetails         `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BztDappReply) Reset() {
	*x = BztDappReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BztDappReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BztDappReply) ProtoMessage() {}

func (x *BztDappReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BztDappReply.ProtoReflect.Descriptor instead.
func (*BztDappReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{29}
}

func (x *BztDappReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BztDappReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BztDappReply) GetData() []*DataDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

type DataDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	DappIcon      string                 `protobuf:"bytes,2,opt,name=dappIcon,proto3" json:"dappIcon,omitempty"`
	DappIntroduce string                 `protobuf:"bytes,3,opt,name=dappIntroduce,proto3" json:"dappIntroduce,omitempty"`
	DappName      string                 `protobuf:"bytes,4,opt,name=dappName,proto3" json:"dappName,omitempty"`
	DappUrl       string                 `protobuf:"bytes,5,opt,name=dappUrl,proto3" json:"dappUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDetails) Reset() {
	*x = DataDetails{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDetails) ProtoMessage() {}

func (x *DataDetails) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDetails.ProtoReflect.Descriptor instead.
func (*DataDetails) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{30}
}

func (x *DataDetails) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DataDetails) GetDappIcon() string {
	if x != nil {
		return x.DappIcon
	}
	return ""
}

func (x *DataDetails) GetDappIntroduce() string {
	if x != nil {
		return x.DappIntroduce
	}
	return ""
}

func (x *DataDetails) GetDappName() string {
	if x != nil {
		return x.DappName
	}
	return ""
}

func (x *DataDetails) GetDappUrl() string {
	if x != nil {
		return x.DappUrl
	}
	return ""
}

type DeployContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployContractRequest) Reset() {
	*x = DeployContractRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployContractRequest) ProtoMessage() {}

func (x *DeployContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployContractRequest.ProtoReflect.Descriptor instead.
func (*DeployContractRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{31}
}

// The response message containing the greetings
type DeployContractReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployContractReply) Reset() {
	*x = DeployContractReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployContractReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployContractReply) ProtoMessage() {}

func (x *DeployContractReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployContractReply.ProtoReflect.Descriptor instead.
func (*DeployContractReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{32}
}

func (x *DeployContractReply) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GetBztOwnerAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBztOwnerAddressRequest) Reset() {
	*x = GetBztOwnerAddressRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBztOwnerAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBztOwnerAddressRequest) ProtoMessage() {}

func (x *GetBztOwnerAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBztOwnerAddressRequest.ProtoReflect.Descriptor instead.
func (*GetBztOwnerAddressRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{33}
}

// The response message containing the greetings
type GetBztOwnerAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BztAddr       string                 `protobuf:"bytes,1,opt,name=bztAddr,proto3" json:"bztAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBztOwnerAddressReply) Reset() {
	*x = GetBztOwnerAddressReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBztOwnerAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBztOwnerAddressReply) ProtoMessage() {}

func (x *GetBztOwnerAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBztOwnerAddressReply.ProtoReflect.Descriptor instead.
func (*GetBztOwnerAddressReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{34}
}

func (x *GetBztOwnerAddressReply) GetBztAddr() string {
	if x != nil {
		return x.BztAddr
	}
	return ""
}

var File_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bhelloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"8\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"2\n" +
	"\x16GetLoginMessageRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"F\n" +
	"\x14GetLoginMessageReply\x12\x1a\n" +
	"\bmetadata\x18\x01 \x01(\tR\bmetadata\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"-\n" +
	"\x11BindWalletRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"S\n" +
	"\x0fBindWalletReply\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"X\n" +
	"\fLoginRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\"\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"0\n" +
	"\x14WalletBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"@\n" +
	"\fTokenBalance\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\"I\n" +
	"\x12WalletBalanceReply\x123\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1b.helloworld.v1.TokenBalanceR\x06tokens\"j\n" +
	"\x16MarketConditionRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"7\n" +
	"\vMarketPrice\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\"J\n" +
	"\x14MarketConditionReply\x122\n" +
	"\x06prices\x18\x01 \x03(\v2\x1a.helloworld.v1.MarketPriceR\x06prices\"b\n" +
	"\x10OpenOrderRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\"*\n" +
	"\x0eOpenOrderReply\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\"}\n" +
	"\x11CloseOrderRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x18\n" +
	"\aorderId\x18\x04 \x01(\tR\aorderId\"!\n" +
	"\x0fCloseOrderReply\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\tR\x02tx\"a\n" +
	"\x11GetAirdropRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bisClaims\x18\x02 \x01(\x04R\bisClaims\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\"W\n" +
	"\x0fGetAirdropReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06txHash\x18\x03 \x01(\tR\x06txHash\"\x14\n" +
	"\x12HealthCheckRequest\"*\n" +
	"\x10HealthCheckReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"]\n" +
	"\x11OrderTradeRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"F\n" +
	"\x0fOrderTradeReply\x123\n" +
	"\x06result\x18\x01 \x03(\v2\x1b.helloworld.v1.OrderDetailsR\x06result\"\x82\x03\n" +
	"\fOrderDetails\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12 \n" +
	"\vopenedPrice\x18\x03 \x01(\tR\vopenedPrice\x12\x1e\n" +
	"\n" +
	"closePrice\x18\x04 \x01(\tR\n" +
	"closePrice\x12\x1e\n" +
	"\n" +
	"profitLoss\x18\x05 \x01(\tR\n" +
	"profitLoss\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1c\n" +
	"\tusersAddr\x18\a \x01(\tR\tusersAddr\x12\x1a\n" +
	"\bisClosed\x18\b \x01(\x04R\bisClosed\x12&\n" +
	"\x0eorderStartTime\x18\t \x01(\x04R\x0eorderStartTime\x12\"\n" +
	"\forderEndTime\x18\n" +
	" \x01(\x04R\forderEndTime\x12\x1e\n" +
	"\n" +
	"openTxHash\x18\v \x01(\tR\n" +
	"openTxHash\x12 \n" +
	"\vcloseTxHash\x18\f \x01(\tR\vcloseTxHash\")\n" +
	"\x13AirdropTradeRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"J\n" +
	"\x11AirdropTradeReply\x125\n" +
	"\x06result\x18\x01 \x03(\v2\x1d.helloworld.v1.AirdropDetailsR\x06result\"\x8c\x01\n" +
	"\x0eAirdropDetails\x12\x1c\n" +
	"\tusersAddr\x18\x01 \x01(\tR\tusersAddr\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05times\x18\x04 \x01(\tR\x05times\x12\x16\n" +
	"\x06txHash\x18\x05 \x01(\tR\x06txHash\"\x10\n" +
	"\x0eBztDappRequest\"l\n" +
	"\fBztDappReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x03(\v2\x1a.helloworld.v1.DataDetailsR\x04data\"\x9b\x01\n" +
	"\vDataDetails\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\x03R\x05appId\x12\x1a\n" +
	"\bdappIcon\x18\x02 \x01(\tR\bdappIcon\x12$\n" +
	"\rdappIntroduce\x18\x03 \x01(\tR\rdappIntroduce\x12\x1a\n" +
	"\bdappName\x18\x04 \x01(\tR\bdappName\x12\x18\n" +
	"\adappUrl\x18\x05 \x01(\tR\adappUrl\"\x17\n" +
	"\x15DeployContractRequest\"-\n" +
	"\x13DeployContractReply\x12\x16\n" +
	"\x06txHash\x18\x01 \x01(\tR\x06txHash\"\x1b\n" +
	"\x19GetBztOwnerAddressRequest\"3\n" +
	"\x17GetBztOwnerAddressReply\x12\x18\n" +
	"\abztAddr\x18\x01 \x01(\tR\abztAddr2\x97\r\n" +
	"\aGreeter\x12f\n" +
	"\bSayHello\x12\x1b.helloworld.v1.HelloRequest\x1a\x19.helloworld.v1.HelloReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/helloworld/{name}/{value}\x12i\n" +
	"\n" +
	"BindWallet\x12 .helloworld.v1.BindWalletRequest\x1a\x1e.helloworld.v1.BindWalletReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/bindWallet\x12}\n" +
	"\x0fGetLoginMessage\x12%.helloworld.v1.GetLoginMessageRequest\x1a#.helloworld.v1.GetLoginMessageReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/getLoginMessage\x12i\n" +
	"\x0fLoginWithWallet\x12\x1b.helloworld.v1.LoginRequest\x1a\x19.helloworld.v1.LoginReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/loginWithWallet\x12u\n" +
	"\rWalletBalance\x12#.helloworld.v1.WalletBalanceRequest\x1a!.helloworld.v1.WalletBalanceReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/walletBalance\x12}\n" +
	"\x0fMarketCondition\x12%.helloworld.v1.MarketConditionRequest\x1a#.helloworld.v1.MarketConditionReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/marketCondition\x12e\n" +
	"\tOpenOrder\x12\x1f.helloworld.v1.OpenOrderRequest\x1a\x1d.helloworld.v1.OpenOrderReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/openOrder\x12i\n" +
	"\n" +
	"CloseOrder\x12 .helloworld.v1.CloseOrderRequest\x1a\x1e.helloworld.v1.CloseOrderReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/closeOrder\x12i\n" +
	"\n" +
	"GetAirdrop\x12 .helloworld.v1.GetAirdropRequest\x1a\x1e.helloworld.v1.GetAirdropReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/getAirdrop\x12]\n" +
	"\x06Health\x12!.helloworld.v1.HealthCheckRequest\x1a\x1f.helloworld.v1.HealthCheckReply\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/health\x12i\n" +
	"\n" +
	"OrderTrade\x12 .helloworld.v1.OrderTradeRequest\x1a\x1e.helloworld.v1.OrderTradeReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/orderTrade\x12q\n" +
	"\fAirdropTrade\x12\".helloworld.v1.AirdropTradeRequest\x1a .helloworld.v1.AirdropTradeReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/airdropTrade\x12X\n" +
	"\aBztDapp\x12\x1d.helloworld.v1.BztDappRequest\x1a\x1b.helloworld.v1.BztDappReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/bzt/dapp\x12y\n" +
	"\x0eDeployContract\x12$.helloworld.v1.DeployContractRequest\x1a\".helloworld.v1.DeployContractReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/deployContract\x12\x89\x01\n" +
	"\x12GetBztOwnerAddress\x12(.helloworld.v1.GetBztOwnerAddressRequest\x1a&.helloworld.v1.GetBztOwnerAddressReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/getBztOwnerAddressBT\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z\x1fvalueguard/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_helloworld_v1_greeter_proto_rawDescData
}

var file_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_helloworld_v1_greeter_proto_goTypes = []any{
	(*HelloRequest)(nil),              // 0: helloworld.v1.HelloRequest
	(*HelloReply)(nil),                // 1: helloworld.v1.HelloReply
	(*GetLoginMessageRequest)(nil),    // 2: helloworld.v1.GetLoginMessageRequest
	(*GetLoginMessageReply)(nil),      // 3: helloworld.v1.GetLoginMessageReply
	(*BindWalletRequest)(nil),         // 4: helloworld.v1.BindWalletRequest
	(*BindWalletReply)(nil),           // 5: helloworld.v1.BindWalletReply
	(*LoginRequest)(nil),              // 6: helloworld.v1.LoginRequest
	(*LoginReply)(nil),                // 7: helloworld.v1.LoginReply
	(*WalletBalanceRequest)(nil),      // 8: helloworld.v1.WalletBalanceRequest
	(*TokenBalance)(nil),              // 9: helloworld.v1.TokenBalance
	(*WalletBalanceReply)(nil),        // 10: helloworld.v1.WalletBalanceReply
	(*MarketConditionRequest)(nil),    // 11: helloworld.v1.MarketConditionRequest
	(*MarketPrice)(nil),               // 12: helloworld.v1.MarketPrice
	(*MarketConditionReply)(nil),      // 13: helloworld.v1.MarketConditionReply
	(*OpenOrderRequest)(nil),          // 14: helloworld.v1.OpenOrderRequest
	(*OpenOrderReply)(nil),            // 15: helloworld.v1.OpenOrderReply
	(*CloseOrderRequest)(nil),         // 16: helloworld.v1.CloseOrderRequest
	(*CloseOrderReply)(nil),           // 17: helloworld.v1.CloseOrderReply
	(*GetAirdropRequest)(nil),         // 18: helloworld.v1.GetAirdropRequest
	(*GetAirdropReply)(nil),           // 19: helloworld.v1.GetAirdropReply
	(*HealthCheckRequest)(nil),        // 20: helloworld.v1.HealthCheckRequest
	(*HealthCheckReply)(nil),          // 21: helloworld.v1.HealthCheckReply
	(*OrderTradeRequest)(nil),         // 22: helloworld.v1.OrderTradeRequest
	(*OrderTradeReply)(nil),           // 23: helloworld.v1.OrderTradeReply
	(*OrderDetails)(nil),              // 24: helloworld.v1.OrderDetails
	(*AirdropTradeRequest)(nil),       // 25: helloworld.v1.AirdropTradeRequest
	(*AirdropTradeReply)(nil),         // 26: helloworld.v1.AirdropTradeReply
	(*AirdropDetails)(nil),            // 27: helloworld.v1.AirdropDetails
	(*BztDappRequest)(nil),            // 28: helloworld.v1.BztDappRequest
	(*BztDappReply)(nil),              // 29: helloworld.v1.BztDappReply
	(*DataDetails)(nil),               // 30: helloworld.v1.DataDetails
	(*DeployContractRequest)(nil),     // 31: helloworld.v1.DeployContractRequest
	(*DeployContractReply)(nil),       // 32: helloworld.v1.DeployContractReply
	(*GetBztOwnerAddressRequest)(nil), // 33: helloworld.v1.GetBztOwnerAddressRequest
	(*GetBztOwnerAddressReply)(nil),   // 34: helloworld.v1.GetBztOwnerAddressReply
}
var file_helloworld_v1_greeter_proto_depIdxs = []int32{
	9,  // 0: helloworld.v1.WalletBalanceReply.tokens:type_name -> helloworld.v1.TokenBalance
	12, // 1: helloworld.v1.MarketConditionReply.prices:type_name -> helloworld.v1.MarketPrice
	24, // 2: helloworld.v1.OrderTradeReply.result:type_name -> helloworld.v1.OrderDetails
	27, // 3: helloworld.v1.AirdropTradeReply.result:type_name -> helloworld.v1.AirdropDetails
	30, // 4: helloworld.v1.BztDappReply.data:type_name -> helloworld.v1.DataDetails
	0,  // 5: helloworld.v1.Greeter.SayHello:input_type -> helloworld.v1.HelloRequest
	4,  // 6: helloworld.v1.Greeter.BindWallet:input_type -> helloworld.v1.BindWalletRequest
	2,  // 7: helloworld.v1.Greeter.GetLoginMessage:input_type -> helloworld.v1.GetLoginMessageRequest
	6,  // 8: helloworld.v1.Greeter.LoginWithWallet:input_type -> helloworld.v1.LoginRequest
	8,  // 9: helloworld.v1.Greeter.WalletBalance:input_type -> helloworld.v1.WalletBalanceRequest
	11, // 10: helloworld.v1.Greeter.MarketCondition:input_type -> helloworld.v1.MarketConditionRequest
	14, // 11: helloworld.v1.Greeter.OpenOrder:input_type -> helloworld.v1.OpenOrderRequest
	16, // 12: helloworld.v1.Greeter.CloseOrder:input_type -> helloworld.v1.CloseOrderRequest
	18, // 13: helloworld.v1.Greeter.GetAirdrop:input_type -> helloworld.v1.GetAirdropRequest
	20, // 14: helloworld.v1.Greeter.Health:input_type -> helloworld.v1.HealthCheckRequest
	22, // 15: helloworld.v1.Greeter.OrderTrade:input_type -> helloworld.v1.OrderTradeRequest
	25, // 16: helloworld.v1.Greeter.AirdropTrade:input_type -> helloworld.v1.AirdropTradeRequest
	28, // 17: helloworld.v1.Greeter.BztDapp:input_type -> helloworld.v1.BztDappRequest
	31, // 18: helloworld.v1.Greeter.DeployContract:input_type -> helloworld.v1.DeployContractRequest
	33, // 19: helloworld.v1.Greeter.GetBztOwnerAddress:input_type -> helloworld.v1.GetBztOwnerAddressRequest
	1,  // 20: helloworld.v1.Greeter.SayHello:output_type -> helloworld.v1.HelloReply
	5,  // 21: helloworld.v1.Greeter.BindWallet:output_type -> helloworld.v1.BindWalletReply
	3,  // 22: helloworld.v1.Greeter.GetLoginMessage:output_type -> helloworld.v1.GetLoginMessageReply
	7,  // 23: helloworld.v1.Greeter.LoginWithWallet:output_type -> helloworld.v1.LoginReply
	10, // 24: helloworld.v1.Greeter.WalletBalance:output_type -> helloworld.v1.WalletBalanceReply
	13, // 25: helloworld.v1.Greeter.MarketCondition:output_type -> helloworld.v1.MarketConditionReply
	15, // 26: helloworld.v1.Greeter.OpenOrder:output_type -> helloworld.v1.OpenOrderReply
	17, // 27: helloworld.v1.Greeter.CloseOrder:output_type -> helloworld.v1.CloseOrderReply
	19, // 28: helloworld.v1.Greeter.GetAirdrop:output_type -> helloworld.v1.GetAirdropReply
	21, // 29: helloworld.v1.Greeter.Health:output_type -> helloworld.v1.HealthCheckReply
	23, // 30: helloworld.v1.Greeter.OrderTrade:output_type -> helloworld.v1.OrderTradeReply
	26, // 31: helloworld.v1.Greeter.AirdropTrade:output_type -> helloworld.v1.AirdropTradeReply
	29, // 32: helloworld.v1.Greeter.BztDapp:output_type -> helloworld.v1.BztDappReply
	32, // 33: helloworld.v1.Greeter.DeployContract:output_type -> helloworld.v1.DeployContractReply
	34, // 34: helloworld.v1.Greeter.GetBztOwnerAddress:output_type -> helloworld.v1.GetBztOwnerAddressReply
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_helloworld_v1_greeter_proto_init() }
func file_helloworld_v1_greeter_proto_init() {
	if File_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_helloworld_v1_greeter_proto = out.File
	file_helloworld_v1_greeter_proto_goTypes = nil
	file_helloworld_v1_greeter_proto_depIdxs = nil
}
