// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: helloworld/v1/greeter.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Greeter_SayHello_FullMethodName           = "/helloworld.v1.Greeter/SayHello"
	Greeter_BindWallet_FullMethodName         = "/helloworld.v1.Greeter/BindWallet"
	Greeter_GetLoginMessage_FullMethodName    = "/helloworld.v1.Greeter/GetLoginMessage"
	Greeter_LoginWithWallet_FullMethodName    = "/helloworld.v1.Greeter/LoginWithWallet"
	Greeter_WalletBalance_FullMethodName      = "/helloworld.v1.Greeter/WalletBalance"
	Greeter_MarketCondition_FullMethodName    = "/helloworld.v1.Greeter/MarketCondition"
	Greeter_OpenOrder_FullMethodName          = "/helloworld.v1.Greeter/OpenOrder"
	Greeter_CloseOrder_FullMethodName         = "/helloworld.v1.Greeter/CloseOrder"
	Greeter_GetAirdrop_FullMethodName         = "/helloworld.v1.Greeter/GetAirdrop"
	Greeter_Health_FullMethodName             = "/helloworld.v1.Greeter/Health"
	Greeter_OrderTrade_FullMethodName         = "/helloworld.v1.Greeter/OrderTrade"
	Greeter_AirdropTrade_FullMethodName       = "/helloworld.v1.Greeter/AirdropTrade"
	Greeter_BztDapp_FullMethodName            = "/helloworld.v1.Greeter/BztDapp"
	Greeter_DeployContract_FullMethodName     = "/helloworld.v1.Greeter/DeployContract"
	Greeter_GetBztDetails_FullMethodName      = "/helloworld.v1.Greeter/GetBztDetails"
	Greeter_GetBztVersion_FullMethodName      = "/helloworld.v1.Greeter/GetBztVersion"
	Greeter_GetConfigs_FullMethodName         = "/helloworld.v1.Greeter/GetConfigs"
	Greeter_GetHistoricalPrice_FullMethodName = "/helloworld.v1.Greeter/GetHistoricalPrice"
	Greeter_GetKLineData_FullMethodName       = "/helloworld.v1.Greeter/GetKLineData"
	Greeter_QueryKLineData_FullMethodName     = "/helloworld.v1.Greeter/QueryKLineData"
	Greeter_ClaimsAirdrop_FullMethodName      = "/helloworld.v1.Greeter/ClaimsAirdrop"
	Greeter_IndexSwitch_FullMethodName        = "/helloworld.v1.Greeter/IndexSwitch"
	Greeter_DeleteIndexSwitch_FullMethodName  = "/helloworld.v1.Greeter/DeleteIndexSwitch"
	Greeter_TradeSwitch_FullMethodName        = "/helloworld.v1.Greeter/TradeSwitch"
	Greeter_BinanceBalance_FullMethodName     = "/helloworld.v1.Greeter/BinanceBalance"
	Greeter_CreateBinanceOrder_FullMethodName = "/helloworld.v1.Greeter/CreateBinanceOrder"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	BindWallet(ctx context.Context, in *BindWalletRequest, opts ...grpc.CallOption) (*BindWalletReply, error)
	GetLoginMessage(ctx context.Context, in *GetLoginMessageRequest, opts ...grpc.CallOption) (*GetLoginMessageReply, error)
	LoginWithWallet(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	WalletBalance(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption) (*WalletBalanceReply, error)
	MarketCondition(ctx context.Context, in *MarketConditionRequest, opts ...grpc.CallOption) (*MarketConditionReply, error)
	OpenOrder(ctx context.Context, in *OpenOrderRequest, opts ...grpc.CallOption) (*OpenOrderReply, error)
	CloseOrder(ctx context.Context, in *CloseOrderRequest, opts ...grpc.CallOption) (*CloseOrderReply, error)
	GetAirdrop(ctx context.Context, in *GetAirdropRequest, opts ...grpc.CallOption) (*GetAirdropReply, error)
	Health(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckReply, error)
	OrderTrade(ctx context.Context, in *OrderTradeRequest, opts ...grpc.CallOption) (*OrderTradeReply, error)
	AirdropTrade(ctx context.Context, in *AirdropTradeRequest, opts ...grpc.CallOption) (*AirdropTradeReply, error)
	BztDapp(ctx context.Context, in *BztDappRequest, opts ...grpc.CallOption) (*BztDappReply, error)
	DeployContract(ctx context.Context, in *DeployContractRequest, opts ...grpc.CallOption) (*DeployContractReply, error)
	GetBztDetails(ctx context.Context, in *GetBztDetailsRequest, opts ...grpc.CallOption) (*GetBztDetailsReply, error)
	GetBztVersion(ctx context.Context, in *GetBztVersionRequest, opts ...grpc.CallOption) (*GetBztVersionReply, error)
	GetConfigs(ctx context.Context, in *GetConfigsRequest, opts ...grpc.CallOption) (*GetConfigsReply, error)
	GetHistoricalPrice(ctx context.Context, in *GetHistoricalPriceRequest, opts ...grpc.CallOption) (*GetHistoricalPriceReply, error)
	GetKLineData(ctx context.Context, in *GetKLineDataRequest, opts ...grpc.CallOption) (*GetKLineDataReply, error)
	QueryKLineData(ctx context.Context, in *QueryKLineDataRequest, opts ...grpc.CallOption) (*QueryKLineDataReply, error)
	ClaimsAirdrop(ctx context.Context, in *ClaimsAirdropRequest, opts ...grpc.CallOption) (*ClaimsAirdropReply, error)
	IndexSwitch(ctx context.Context, in *IndexSwitchRequest, opts ...grpc.CallOption) (*IndexSwitchReply, error)
	DeleteIndexSwitch(ctx context.Context, in *DeleteIndexSwitchRequest, opts ...grpc.CallOption) (*DeleteIndexSwitchReply, error)
	TradeSwitch(ctx context.Context, in *TradeSwitchRequest, opts ...grpc.CallOption) (*TradeSwitchReply, error)
	BinanceBalance(ctx context.Context, in *BinanceBalanceRequest, opts ...grpc.CallOption) (*BinanceBalanceReply, error)
	CreateBinanceOrder(ctx context.Context, in *CreateBinanceOrderRequest, opts ...grpc.CallOption) (*CreateBinanceOrderReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) BindWallet(ctx context.Context, in *BindWalletRequest, opts ...grpc.CallOption) (*BindWalletReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindWalletReply)
	err := c.cc.Invoke(ctx, Greeter_BindWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetLoginMessage(ctx context.Context, in *GetLoginMessageRequest, opts ...grpc.CallOption) (*GetLoginMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoginMessageReply)
	err := c.cc.Invoke(ctx, Greeter_GetLoginMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) LoginWithWallet(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, Greeter_LoginWithWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) WalletBalance(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption) (*WalletBalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletBalanceReply)
	err := c.cc.Invoke(ctx, Greeter_WalletBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) MarketCondition(ctx context.Context, in *MarketConditionRequest, opts ...grpc.CallOption) (*MarketConditionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketConditionReply)
	err := c.cc.Invoke(ctx, Greeter_MarketCondition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) OpenOrder(ctx context.Context, in *OpenOrderRequest, opts ...grpc.CallOption) (*OpenOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenOrderReply)
	err := c.cc.Invoke(ctx, Greeter_OpenOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CloseOrder(ctx context.Context, in *CloseOrderRequest, opts ...grpc.CallOption) (*CloseOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseOrderReply)
	err := c.cc.Invoke(ctx, Greeter_CloseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetAirdrop(ctx context.Context, in *GetAirdropRequest, opts ...grpc.CallOption) (*GetAirdropReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAirdropReply)
	err := c.cc.Invoke(ctx, Greeter_GetAirdrop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Health(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckReply)
	err := c.cc.Invoke(ctx, Greeter_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) OrderTrade(ctx context.Context, in *OrderTradeRequest, opts ...grpc.CallOption) (*OrderTradeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderTradeReply)
	err := c.cc.Invoke(ctx, Greeter_OrderTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) AirdropTrade(ctx context.Context, in *AirdropTradeRequest, opts ...grpc.CallOption) (*AirdropTradeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AirdropTradeReply)
	err := c.cc.Invoke(ctx, Greeter_AirdropTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) BztDapp(ctx context.Context, in *BztDappRequest, opts ...grpc.CallOption) (*BztDappReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BztDappReply)
	err := c.cc.Invoke(ctx, Greeter_BztDapp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) DeployContract(ctx context.Context, in *DeployContractRequest, opts ...grpc.CallOption) (*DeployContractReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployContractReply)
	err := c.cc.Invoke(ctx, Greeter_DeployContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBztDetails(ctx context.Context, in *GetBztDetailsRequest, opts ...grpc.CallOption) (*GetBztDetailsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBztDetailsReply)
	err := c.cc.Invoke(ctx, Greeter_GetBztDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBztVersion(ctx context.Context, in *GetBztVersionRequest, opts ...grpc.CallOption) (*GetBztVersionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBztVersionReply)
	err := c.cc.Invoke(ctx, Greeter_GetBztVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetConfigs(ctx context.Context, in *GetConfigsRequest, opts ...grpc.CallOption) (*GetConfigsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigsReply)
	err := c.cc.Invoke(ctx, Greeter_GetConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetHistoricalPrice(ctx context.Context, in *GetHistoricalPriceRequest, opts ...grpc.CallOption) (*GetHistoricalPriceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoricalPriceReply)
	err := c.cc.Invoke(ctx, Greeter_GetHistoricalPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetKLineData(ctx context.Context, in *GetKLineDataRequest, opts ...grpc.CallOption) (*GetKLineDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKLineDataReply)
	err := c.cc.Invoke(ctx, Greeter_GetKLineData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) QueryKLineData(ctx context.Context, in *QueryKLineDataRequest, opts ...grpc.CallOption) (*QueryKLineDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryKLineDataReply)
	err := c.cc.Invoke(ctx, Greeter_QueryKLineData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ClaimsAirdrop(ctx context.Context, in *ClaimsAirdropRequest, opts ...grpc.CallOption) (*ClaimsAirdropReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimsAirdropReply)
	err := c.cc.Invoke(ctx, Greeter_ClaimsAirdrop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) IndexSwitch(ctx context.Context, in *IndexSwitchRequest, opts ...grpc.CallOption) (*IndexSwitchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexSwitchReply)
	err := c.cc.Invoke(ctx, Greeter_IndexSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) DeleteIndexSwitch(ctx context.Context, in *DeleteIndexSwitchRequest, opts ...grpc.CallOption) (*DeleteIndexSwitchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexSwitchReply)
	err := c.cc.Invoke(ctx, Greeter_DeleteIndexSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) TradeSwitch(ctx context.Context, in *TradeSwitchRequest, opts ...grpc.CallOption) (*TradeSwitchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeSwitchReply)
	err := c.cc.Invoke(ctx, Greeter_TradeSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) BinanceBalance(ctx context.Context, in *BinanceBalanceRequest, opts ...grpc.CallOption) (*BinanceBalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinanceBalanceReply)
	err := c.cc.Invoke(ctx, Greeter_BinanceBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CreateBinanceOrder(ctx context.Context, in *CreateBinanceOrderRequest, opts ...grpc.CallOption) (*CreateBinanceOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBinanceOrderReply)
	err := c.cc.Invoke(ctx, Greeter_CreateBinanceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility.
//
// The greeting service definition.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	BindWallet(context.Context, *BindWalletRequest) (*BindWalletReply, error)
	GetLoginMessage(context.Context, *GetLoginMessageRequest) (*GetLoginMessageReply, error)
	LoginWithWallet(context.Context, *LoginRequest) (*LoginReply, error)
	WalletBalance(context.Context, *WalletBalanceRequest) (*WalletBalanceReply, error)
	MarketCondition(context.Context, *MarketConditionRequest) (*MarketConditionReply, error)
	OpenOrder(context.Context, *OpenOrderRequest) (*OpenOrderReply, error)
	CloseOrder(context.Context, *CloseOrderRequest) (*CloseOrderReply, error)
	GetAirdrop(context.Context, *GetAirdropRequest) (*GetAirdropReply, error)
	Health(context.Context, *HealthCheckRequest) (*HealthCheckReply, error)
	OrderTrade(context.Context, *OrderTradeRequest) (*OrderTradeReply, error)
	AirdropTrade(context.Context, *AirdropTradeRequest) (*AirdropTradeReply, error)
	BztDapp(context.Context, *BztDappRequest) (*BztDappReply, error)
	DeployContract(context.Context, *DeployContractRequest) (*DeployContractReply, error)
	GetBztDetails(context.Context, *GetBztDetailsRequest) (*GetBztDetailsReply, error)
	GetBztVersion(context.Context, *GetBztVersionRequest) (*GetBztVersionReply, error)
	GetConfigs(context.Context, *GetConfigsRequest) (*GetConfigsReply, error)
	GetHistoricalPrice(context.Context, *GetHistoricalPriceRequest) (*GetHistoricalPriceReply, error)
	GetKLineData(context.Context, *GetKLineDataRequest) (*GetKLineDataReply, error)
	QueryKLineData(context.Context, *QueryKLineDataRequest) (*QueryKLineDataReply, error)
	ClaimsAirdrop(context.Context, *ClaimsAirdropRequest) (*ClaimsAirdropReply, error)
	IndexSwitch(context.Context, *IndexSwitchRequest) (*IndexSwitchReply, error)
	DeleteIndexSwitch(context.Context, *DeleteIndexSwitchRequest) (*DeleteIndexSwitchReply, error)
	TradeSwitch(context.Context, *TradeSwitchRequest) (*TradeSwitchReply, error)
	BinanceBalance(context.Context, *BinanceBalanceRequest) (*BinanceBalanceReply, error)
	CreateBinanceOrder(context.Context, *CreateBinanceOrderRequest) (*CreateBinanceOrderReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreeterServer struct{}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) BindWallet(context.Context, *BindWalletRequest) (*BindWalletReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindWallet not implemented")
}
func (UnimplementedGreeterServer) GetLoginMessage(context.Context, *GetLoginMessageRequest) (*GetLoginMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoginMessage not implemented")
}
func (UnimplementedGreeterServer) LoginWithWallet(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithWallet not implemented")
}
func (UnimplementedGreeterServer) WalletBalance(context.Context, *WalletBalanceRequest) (*WalletBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletBalance not implemented")
}
func (UnimplementedGreeterServer) MarketCondition(context.Context, *MarketConditionRequest) (*MarketConditionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketCondition not implemented")
}
func (UnimplementedGreeterServer) OpenOrder(context.Context, *OpenOrderRequest) (*OpenOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenOrder not implemented")
}
func (UnimplementedGreeterServer) CloseOrder(context.Context, *CloseOrderRequest) (*CloseOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseOrder not implemented")
}
func (UnimplementedGreeterServer) GetAirdrop(context.Context, *GetAirdropRequest) (*GetAirdropReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAirdrop not implemented")
}
func (UnimplementedGreeterServer) Health(context.Context, *HealthCheckRequest) (*HealthCheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGreeterServer) OrderTrade(context.Context, *OrderTradeRequest) (*OrderTradeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderTrade not implemented")
}
func (UnimplementedGreeterServer) AirdropTrade(context.Context, *AirdropTradeRequest) (*AirdropTradeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AirdropTrade not implemented")
}
func (UnimplementedGreeterServer) BztDapp(context.Context, *BztDappRequest) (*BztDappReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BztDapp not implemented")
}
func (UnimplementedGreeterServer) DeployContract(context.Context, *DeployContractRequest) (*DeployContractReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployContract not implemented")
}
func (UnimplementedGreeterServer) GetBztDetails(context.Context, *GetBztDetailsRequest) (*GetBztDetailsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBztDetails not implemented")
}
func (UnimplementedGreeterServer) GetBztVersion(context.Context, *GetBztVersionRequest) (*GetBztVersionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBztVersion not implemented")
}
func (UnimplementedGreeterServer) GetConfigs(context.Context, *GetConfigsRequest) (*GetConfigsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigs not implemented")
}
func (UnimplementedGreeterServer) GetHistoricalPrice(context.Context, *GetHistoricalPriceRequest) (*GetHistoricalPriceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoricalPrice not implemented")
}
func (UnimplementedGreeterServer) GetKLineData(context.Context, *GetKLineDataRequest) (*GetKLineDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKLineData not implemented")
}
func (UnimplementedGreeterServer) QueryKLineData(context.Context, *QueryKLineDataRequest) (*QueryKLineDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryKLineData not implemented")
}
func (UnimplementedGreeterServer) ClaimsAirdrop(context.Context, *ClaimsAirdropRequest) (*ClaimsAirdropReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimsAirdrop not implemented")
}
func (UnimplementedGreeterServer) IndexSwitch(context.Context, *IndexSwitchRequest) (*IndexSwitchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexSwitch not implemented")
}
func (UnimplementedGreeterServer) DeleteIndexSwitch(context.Context, *DeleteIndexSwitchRequest) (*DeleteIndexSwitchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIndexSwitch not implemented")
}
func (UnimplementedGreeterServer) TradeSwitch(context.Context, *TradeSwitchRequest) (*TradeSwitchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeSwitch not implemented")
}
func (UnimplementedGreeterServer) BinanceBalance(context.Context, *BinanceBalanceRequest) (*BinanceBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BinanceBalance not implemented")
}
func (UnimplementedGreeterServer) CreateBinanceOrder(context.Context, *CreateBinanceOrderRequest) (*CreateBinanceOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBinanceOrder not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}
func (UnimplementedGreeterServer) testEmbeddedByValue()                 {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	// If the following call pancis, it indicates UnimplementedGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_BindWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).BindWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_BindWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).BindWallet(ctx, req.(*BindWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetLoginMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoginMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetLoginMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetLoginMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetLoginMessage(ctx, req.(*GetLoginMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_LoginWithWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).LoginWithWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_LoginWithWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).LoginWithWallet(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_WalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).WalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_WalletBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).WalletBalance(ctx, req.(*WalletBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_MarketCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketConditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).MarketCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_MarketCondition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).MarketCondition(ctx, req.(*MarketConditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_OpenOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).OpenOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_OpenOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).OpenOrder(ctx, req.(*OpenOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CloseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CloseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_CloseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CloseOrder(ctx, req.(*CloseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetAirdrop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAirdropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetAirdrop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetAirdrop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetAirdrop(ctx, req.(*GetAirdropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Health(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_OrderTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).OrderTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_OrderTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).OrderTrade(ctx, req.(*OrderTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_AirdropTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AirdropTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).AirdropTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_AirdropTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).AirdropTrade(ctx, req.(*AirdropTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_BztDapp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BztDappRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).BztDapp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_BztDapp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).BztDapp(ctx, req.(*BztDappRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_DeployContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeployContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_DeployContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeployContract(ctx, req.(*DeployContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBztDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBztDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBztDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetBztDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBztDetails(ctx, req.(*GetBztDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBztVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBztVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBztVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetBztVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBztVersion(ctx, req.(*GetBztVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetConfigs(ctx, req.(*GetConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetHistoricalPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoricalPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetHistoricalPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetHistoricalPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetHistoricalPrice(ctx, req.(*GetHistoricalPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetKLineData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKLineDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetKLineData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetKLineData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetKLineData(ctx, req.(*GetKLineDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_QueryKLineData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKLineDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).QueryKLineData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_QueryKLineData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).QueryKLineData(ctx, req.(*QueryKLineDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ClaimsAirdrop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimsAirdropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).ClaimsAirdrop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_ClaimsAirdrop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).ClaimsAirdrop(ctx, req.(*ClaimsAirdropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_IndexSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).IndexSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_IndexSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).IndexSwitch(ctx, req.(*IndexSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_DeleteIndexSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeleteIndexSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_DeleteIndexSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeleteIndexSwitch(ctx, req.(*DeleteIndexSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_TradeSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).TradeSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_TradeSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).TradeSwitch(ctx, req.(*TradeSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_BinanceBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinanceBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).BinanceBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_BinanceBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).BinanceBalance(ctx, req.(*BinanceBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CreateBinanceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBinanceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateBinanceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_CreateBinanceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateBinanceOrder(ctx, req.(*CreateBinanceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "BindWallet",
			Handler:    _Greeter_BindWallet_Handler,
		},
		{
			MethodName: "GetLoginMessage",
			Handler:    _Greeter_GetLoginMessage_Handler,
		},
		{
			MethodName: "LoginWithWallet",
			Handler:    _Greeter_LoginWithWallet_Handler,
		},
		{
			MethodName: "WalletBalance",
			Handler:    _Greeter_WalletBalance_Handler,
		},
		{
			MethodName: "MarketCondition",
			Handler:    _Greeter_MarketCondition_Handler,
		},
		{
			MethodName: "OpenOrder",
			Handler:    _Greeter_OpenOrder_Handler,
		},
		{
			MethodName: "CloseOrder",
			Handler:    _Greeter_CloseOrder_Handler,
		},
		{
			MethodName: "GetAirdrop",
			Handler:    _Greeter_GetAirdrop_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Greeter_Health_Handler,
		},
		{
			MethodName: "OrderTrade",
			Handler:    _Greeter_OrderTrade_Handler,
		},
		{
			MethodName: "AirdropTrade",
			Handler:    _Greeter_AirdropTrade_Handler,
		},
		{
			MethodName: "BztDapp",
			Handler:    _Greeter_BztDapp_Handler,
		},
		{
			MethodName: "DeployContract",
			Handler:    _Greeter_DeployContract_Handler,
		},
		{
			MethodName: "GetBztDetails",
			Handler:    _Greeter_GetBztDetails_Handler,
		},
		{
			MethodName: "GetBztVersion",
			Handler:    _Greeter_GetBztVersion_Handler,
		},
		{
			MethodName: "GetConfigs",
			Handler:    _Greeter_GetConfigs_Handler,
		},
		{
			MethodName: "GetHistoricalPrice",
			Handler:    _Greeter_GetHistoricalPrice_Handler,
		},
		{
			MethodName: "GetKLineData",
			Handler:    _Greeter_GetKLineData_Handler,
		},
		{
			MethodName: "QueryKLineData",
			Handler:    _Greeter_QueryKLineData_Handler,
		},
		{
			MethodName: "ClaimsAirdrop",
			Handler:    _Greeter_ClaimsAirdrop_Handler,
		},
		{
			MethodName: "IndexSwitch",
			Handler:    _Greeter_IndexSwitch_Handler,
		},
		{
			MethodName: "DeleteIndexSwitch",
			Handler:    _Greeter_DeleteIndexSwitch_Handler,
		},
		{
			MethodName: "TradeSwitch",
			Handler:    _Greeter_TradeSwitch_Handler,
		},
		{
			MethodName: "BinanceBalance",
			Handler:    _Greeter_BinanceBalance_Handler,
		},
		{
			MethodName: "CreateBinanceOrder",
			Handler:    _Greeter_CreateBinanceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/v1/greeter.proto",
}
